version: '3.7'
services: 
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pet_store'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '2001:3306'
    expose:
      - '2001'
    volumes:
      - my-db:/var/lib/mysql
  pet-store-backend: 
    build: 
     context: ../../
    network_mode: "host"
    environment:
      - NODE_ENV=dev
      - EXPOSE_PORT=3050
    volumes:
      - type: bind
        source: ../../
        target: /usr/src/app
    ports: 
      - "3050:3050"
    depends_on:
      - mysql
volumes:
  my-db: